kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-cephfs-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage-tier: ci
